### ISSUE TITLE
Add CircleCI

### ISSUE THREAD

**Issue by growdev** [ConvertKit/convertkit-paid-memberships-pro#13]
@gammons Please add this repo to the CircleCi. Thanks!

**Comment by gammons** [comment]
![image](https://user-images.githubusercontent.com/38560/46869359-79464800-cdf9-11e8-89b7-1aa03b169cb1.png)

sample.yml file:

```yml
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: phpunit
```
